library:
  join: knockback-inspector.js
  minimize: true
  files:
    - src/lib/kbi_core.coffee
    - src/view_models/kbi_node_view_model.coffee
    - src/views/kbi_collection_node_view.coffee
    - src/views/kbi_model_node_view.coffee
    - src/lib/kbi_string_template_engine.coffee
    - src/models/kbi_fetched.coffee

tests:
  output: ./build
  directories:
    - test/knockback_inspector_core
    - test/packaging
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
    build:
      no_files_ok: ['test/packaging']
