library:
  join: knockback-inspector.js
  compress: true
  files:
    - src/lib/kbi_core.coffee
    - src/view_models/kbi_node_view_model.coffee
    - src/views/kbi_collection_node_view.coffee
    - src/views/kbi_model_node_view.coffee
    - src/lib/kbi_string_template_engine.coffee
    - src/models/kbi_fetched.coffee

tests:
  output: build
  directories:
    - test/core
    - test/packaging
  modes:
    build:
      bundles:
        test/packaging/build/bundle.js:
          underscore: underscore
          backbone: backbone
          backbone-relational: vendor/backbone-relational-latest.js
          knockout: vendor/knockout-latest.js
          knockback: knockback
          knockback-inspector: knockback-inspector.js
      no_files_ok: ['test/packaging']
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'

postinstall:
  commands:
    - 'cp underscore vendor/underscore-latest.js'
    - 'cp backbone vendor/backbone-latest.js'
    - 'cp knockback vendor/knockback-latest.js'
    - 'cp knockback/vendor/backbone-relational-latest.js vendor/backbone-relational-latest.js'
