// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  kbi.TemplateSource = (function() {

    function TemplateSource(template_string) {
      this.template_string = template_string;
    }

    TemplateSource.prototype.text = function(value) {
      return this.template_string;
    };

    return TemplateSource;

  })();

  kbi.TemplateEngine = (function(_super) {

    __extends(TemplateEngine, _super);

    function TemplateEngine() {
      this.allowTemplateRewriting = false;
    }

    TemplateEngine.prototype.makeTemplateSource = function(template) {
      switch (template) {
        case 'kbi_model_node':
          return new kbi.TemplateSource(kbi.ModelNodeView);
        case 'kbi_collection_node':
          return new kbi.TemplateSource(kbi.CollectionNodeView);
        default:
          return ko.nativeTemplateEngine.prototype.makeTemplateSource.apply(this, arguments);
      }
    };

    return TemplateEngine;

  })(ko.nativeTemplateEngine);

}).call(this);
