// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  kbi.StringTemplateSource = (function() {

    function StringTemplateSource(template_string) {
      this.template_string = template_string;
    }

    StringTemplateSource.prototype.text = function(value) {
      return this.template_string;
    };

    return StringTemplateSource;

  })();

  kbi.StringTemplateEngine = (function(_super) {

    __extends(StringTemplateEngine, _super);

    function StringTemplateEngine() {
      this.allowTemplateRewriting = false;
    }

    StringTemplateEngine.prototype.makeTemplateSource = function(template) {
      switch (template) {
        case 'kbi_model_node':
          return new kbi.StringTemplateSource(kbi.ModelNodeView);
        case 'kbi_collection_node':
          return new kbi.StringTemplateSource(kbi.CollectionNodeView);
        default:
          return ko.nativeTemplateEngine.prototype.makeTemplateSource.apply(this, arguments);
      }
    };

    return StringTemplateEngine;

  })(ko.nativeTemplateEngine);

}).call(this);
